import Head from 'next/head';
import Card from '../components/Card';

function HomePage() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Card>Some stuff</Card>
      </main>

      <footer></footer>
    </div>
  );
}

export default HomePage;
