import { useEffect, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useDispatch, useSelector } from 'react-redux';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faClock, faPencil } from '@fortawesome/free-solid-svg-icons';
import ListService from '../services/ListService';
import listActions from '../redux/actions/list.actions';
import Card from '../components/Card';
import ListCreationModal from '../components/Functional/ListCreationModal';

const List: NextPage = () => {
  const dispatch = useDispatch();
  const [isListCreationModalShowing, setIsListCreationModalShowing] =
    useState<boolean>(false);
  const { userOwned = [] } = useSelector((state: any) => state.list);

  useEffect(() => {
    (async () => {
      const { success, data, error } = await ListService.getAll();

      if (success) {
        dispatch(listActions.getAll(data.lists));
      }
    })();
  }, [dispatch]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          {userOwned.map((list: any) => {
            return (
              <Card key={list._id}>
                <>
                  <h3 className="text-lg font-semibold">{list.name}</h3>
                  <h4 className="text-sm font-thin">{list.description}</h4>

                  <div className="flex flex-col p-2 shadow-inner rounded bg-gray-200 mt-2">
                    {list.urls.map((link: string) => {
                      return (
                        <a
                          className="bg-white text-purple-400 font-semibold text-sm py-1 px-2 rounded my-1 shadow-md"
                          key={link}
                          href={link}
                          rel="noopener noreferrer"
                          target="_blank"
                        >
                          {link}
                        </a>
                      );
                    })}
                  </div>

                  <div className="grid grid-cols-2 gap-x-2 mt-2 border border-gray-200 rounded p-2 shadow-inner">
                    <button className="bg-purple-500 p-1 font-semibold rounded text-sm text-white">
                      <FontAwesomeIcon
                        icon={faPencil}
                        className="mr-1"
                        size="sm"
                      />
                      Edit
                    </button>
                    <button className="bg-purple-600 p-1 font-semibold rounded text-sm text-white">
                      <FontAwesomeIcon
                        icon={faClock}
                        className="mr-1"
                        size="sm"
                      />
                      Schedule
                    </button>
                  </div>
                </>
              </Card>
            );
          })}
        </div>

        <ListCreationModal
          isShowing={isListCreationModalShowing}
          setIsShowing={setIsListCreationModalShowing}
        />
      </main>
    </div>
  );
};

export default List;
