import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import { useDispatch } from 'react-redux';
import authActions from '../redux/actions/auth.actions';
import LocalStorage from '../utils/localStorage';

const Logout: NextPage = () => {
  const router = useRouter();
  const dispatch = useDispatch();

  useEffect(() => {
    LocalStorage.clear();
    router.push('/');
    dispatch(
      authActions.logIn({
        firstName: '',
        lastName: '',
        email: '',
        token: null,
        _id: '',
      })
    );
  }, [router, dispatch]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main></main>

      <footer></footer>
    </div>
  );
};

export default Logout;
